[package]
name = "can-hal-isotp-examples"
version.workspace = true
edition = "2021"
publish = false

[lints]
workspace = true

[[example]]
name = "loopback"

[[example]]
name = "isotp_send"

[[example]]
name = "isotp_receive"

[[example]]
name = "kernel_interop"

[[example]]
name = "extended_addressing"

[[example]]
name = "functional_addressing"

[[example]]
name = "loopback_fd"

[[example]]
name = "cross_adapter"

[[example]]
name = "cross_adapter_fd"

[dependencies]
can-hal-isotp = { path = "../../can-hal-isotp" }
can-hal-socketcan = { path = "../../can-hal-socketcan" }
can-hal-pcan = { path = "../../can-hal-pcan" }
can-hal-kvaser = { path = "../../can-hal-kvaser" }
can-hal = { workspace = true }

[dev-dependencies]
libc = "0.2"
